// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhsgeWlX7tl6-Lfw6W3_oqWyDU4nsjiMM',
    appId: '1:302736752616:web:904458c7ab7c49bf266e5d',
    messagingSenderId: '302736752616',
    projectId: 'iotproject-4d97d',
    authDomain: 'iotproject-4d97d.firebaseapp.com',
    databaseURL: 'https://iotproject-4d97d-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-4d97d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcVtlgKHBdwSCFZxt2dmnRaOZk46LDaE0',
    appId: '1:302736752616:android:37f4a6e96562a08a266e5d',
    messagingSenderId: '302736752616',
    projectId: 'iotproject-4d97d',
    databaseURL: 'https://iotproject-4d97d-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-4d97d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfG8_FObCkvQEoYA4QH9iLB8hludLutIA',
    appId: '1:302736752616:ios:7323596ffa6b5c08266e5d',
    messagingSenderId: '302736752616',
    projectId: 'iotproject-4d97d',
    databaseURL: 'https://iotproject-4d97d-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-4d97d.appspot.com',
    iosClientId:
    '302736752616-mntclcftpvso6iu61pfv2modo1sa4coe.apps.googleusercontent.com',
    iosBundleId: 'com.example.vfactus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfG8_FObCkvQEoYA4QH9iLB8hludLutIA',
    appId: '1:302736752616:ios:7323596ffa6b5c08266e5d',
    messagingSenderId: '302736752616',
    projectId: 'iotproject-4d97d',
    databaseURL: 'https://iotproject-4d97d-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-4d97d.appspot.com',
    iosClientId:
    '302736752616-mntclcftpvso6iu61pfv2modo1sa4coe.apps.googleusercontent.com',
    iosBundleId: 'com.example.vfactus',
  );
}
